"""
AI Employee - Hugging Face Spaces Demo
Gradio UI for AI Employee Platinum Tier
"""

import gradio as gr
from datetime import datetime
import json

# Mock AI Employee functions (replace with actual logic)
def get_vault_status():
    """Get current vault status"""
    return {
        "pending_approvals": 3,
        "completed_today": 12,
        "total_actions": 156,
        "last_sync": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

def process_approval(action_id, decision):
    """Process approval decision"""
    return {
        "action_id": action_id,
        "decision": decision,
        "timestamp": datetime.now().isoformat(),
        "status": "processed"
    }

def create_draft(action_type, content):
    """Create a draft action"""
    return f"""
---
type: {action_type}
created: {datetime.now().isoformat()}
status: draft
---

# Draft Action

{content}

---
*Generated by AI Employee*
"""

def get_recent_actions():
    """Get recent actions from vault"""
    return [
        {"id": "ACT-001", "type": "Email", "status": "Pending", "time": "10 min ago"},
        {"id": "ACT-002", "type": "Social Post", "status": "Approved", "time": "1 hour ago"},
        {"id": "ACT-003", "type": "Invoice", "status": "Completed", "time": "2 hours ago"},
        {"id": "ACT-004", "type": "Lead Followup", "status": "Pending", "time": "3 hours ago"},
    ]

# Gradio UI
with gr.Blocks(title="AI Employee - Platinum Tier", theme=gr.themes.Soft()) as demo:
    
    gr.Markdown("""
    # 🤖 AI Employee - Platinum Tier
    
    **Autonomous Digital Worker**
    
    - Monitors emails, social media, and leads
    - Creates drafts autonomously
    - Requires human approval for actions
    - Complete audit trail
    """)
    
    with gr.Tabs():
        
        # Tab 1: Dashboard
        with gr.TabItem("📊 Dashboard"):
            status_json = gr.JSON(label="Vault Status")
            refresh_btn = gr.Button("Refresh Status")
            
            def update_status():
                return get_vault_status()
            
            refresh_btn.click(fn=update_status, outputs=status_json)
        
        # Tab 2: Pending Approvals
        with gr.TabItem("📋 Pending Approvals"):
            actions_list = gr.JSON(label="Recent Actions")
            
            with gr.Row():
                action_id_input = gr.Textbox(label="Action ID", placeholder="ACT-001")
                decision_radio = gr.Radio(
                    choices=["Approve", "Reject"],
                    label="Decision"
                )
                process_btn = gr.Button("Process")
            
            result_json = gr.JSON(label="Result")
            
            def handle_approval(action_id, decision):
                return process_approval(action_id, decision)
            
            process_btn.click(
                fn=handle_approval,
                inputs=[action_id_input, decision_radio],
                outputs=result_json
            )
            
            demo.load(fn=lambda: get_recent_actions(), outputs=actions_list)
        
        # Tab 3: Create Draft
        with gr.TabItem("✏️ Create Draft"):
            draft_type = gr.Dropdown(
                choices=["Email", "Social Post", "Invoice", "Lead Response"],
                label="Action Type"
            )
            draft_content = gr.Textbox(
                label="Content",
                placeholder="Enter content for draft...",
                lines=5
            )
            create_btn = gr.Button("Create Draft")
            draft_output = gr.Textbox(label="Generated Draft", lines=10)
            
            create_btn.click(
                fn=create_draft,
                inputs=[draft_type, draft_content],
                outputs=draft_output
            )
        
        # Tab 4: Documentation
        with gr.TabItem("📖 Documentation"):
            gr.Markdown("""
            ## AI Employee Features
            
            ### Watchers
            - Gmail Monitor
            - Social Media (Twitter, Facebook, LinkedIn)
            - Lead Capture
            
            ### Actions
            - Email Drafting & Sending
            - Social Media Posting
            - Invoice Creation (Odoo)
            - Lead Follow-up
            
            ### Security
            - Human-in-the-Loop Approval
            - DRY_RUN Mode
            - Complete Audit Logs
            - No credentials synced
            
            ### Deployment
            - Local Mode (Your PC)
            - Cloud VM (24/7)
            - Hugging Face Spaces (Demo)
            """)
    
    gr.Markdown("""
    ---
    **AI Employee Platinum Tier** | Built with Claude Code + Python
    """)

# Launch
if __name__ == "__main__":
    demo.launch()
